openapi: 3.2.0
info:
  title: Plausible Sites Shared Links API
  description: The Plausible Sites API enables developers to programmatically manage sites, teams, goals, custom properties, shared links, and guest access within their Plausible account.
  version: 1.0.0
  contact:
    name: Plausible Support
    url: https://plausible.io/contact
  license:
    name: AGPL-3.0
    url: https://github.com/plausible/analytics/blob/master/LICENSE.md
servers:
- url: https://plausible.io
  description: Plausible Cloud
security:
- bearerAuth: []
tags:
- name: Shared Links
paths:
  /api/v1/sites/shared-links:
    put:
      tags:
      - Shared Links
      summary: Create or find shared link
      operationId: upsertSharedLink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SharedLink'
      responses:
        '200':
          description: Created or returned.
components:
  schemas:
    SharedLink:
      type: object
      properties:
        site_id:
          type: string
        name:
          type: string
        password:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
